### ISSUE TITLE
Please attribute queries that were copied

### ISSUE THREAD

**Issue by lawndoc** [apacketofsweets/Azure-Threat-Hunters-Toolkit#1]
Hi @apacketofsweets,
I saw that you had recently starred my own [advanced hunting repo](https://github.com/lawndoc/AdvancedHuntingQueries), which led me to checking out your profile and this repo. I noticed that you copied some of my queries over here and renamed them. I don't have a problem with that because I posted them so that others could use them. But I'd appreciate if you attributed the queries to me somewhere in the files you copied.

Thanks.
C.J.

**Comment by apacketofsweets** [comment]
Hey CJ. Of course, attribution added into the readme, let me know if that's sufficient.

**Comment by lawndoc** [comment]
Yep thanks! Appreciate it!
